name = "RLAOpInf"
uuid = "87de30fd-0b8f-422f-9fbb-b2b1aa9e86d2"
version = "0.1.0"
authors = ["Vivak Patel <vp314@users.noreply.github.com>"]

[deps]
LiftAndLearn = "192fc49d-b0e9-4795-8347-9ce9b8a8946d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolynomialModelReductionDataset = "e73a8ff0-27fc-4bea-a65d-4cea79111efd"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RLinearAlgebra = "da1d211a-c3bc-43b2-b5d0-ce83f16a0f3a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UniqueKronecker = "dd29a912-d12a-442e-ae57-6933397c0393"

[compat]
LiftAndLearn = "1.0.1"
LinearAlgebra = "1.12.0"
PolynomialModelReductionDataset = "0.1.1"
ProgressMeter = "1.11.0"
RLinearAlgebra = "0.2.4"
Random = "1.11.0"
Statistics = "1.11.1"
UniqueKronecker = "0.2.0"
julia = "1.11.7"
